# https://github.com/n0rthernl1ghts/s6-rootfs/pkgs/container/s6-rootfs#recommended-way-to-integrate-with-your-image-example
# ---------------------
# Build root filesystem
# ---------------------
FROM scratch AS rootfs

# Copy over base files
COPY ["./rootfs-s6-rc", "/"]

# Install S6
COPY --from=yanhao98/s6-rootfs@sha256:ca8ee32519ebc8df25755c321eb8345417729e0d7645769ef8f74af8aa405121 ["/", "/"]


# ---------------------
# Build image
# ---------------------
FROM alpine:3@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd

ENV TZ=Asia/Shanghai
RUN apk add alpine-conf && \
  /sbin/setup-timezone -z Asia/Shanghai && \
  apk del alpine-conf

ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data
RUN apk add --update --no-cache curl

WORKDIR /opt
COPY --from=rootfs ["/", "/"]

COPY --from=adguard/adguardhome:latest@sha256:f890b77505e410e295cc96830632b46075d7263cef52c158f9331348c98e1228 ["/opt/adguardhome", "/opt/adguardhome"]
VOLUME ["/opt/adguardhome/work", "/opt/adguardhome/conf"]

COPY --from=yanhao98/caddy-dns-cloudflare:latest@sha256:d443dd1c71c2c397882c358aab467ca3be3009393610475a656bee6b10ec37a0 ["/usr/bin/caddy", "/opt/caddy/caddy"]

# S6 configuration - not required
# See: https://github.com/just-containers/s6-overlay#customizing-s6-overlay-behaviour
# ENV S6_KEEP_ENV=1
# ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2
# ENV S6_CMD_RECEIVE_SIGNALS=1

# Important, this is required for S6 to work
ENTRYPOINT ["/init"]