# https://github.com/n0rthernl1ghts/s6-rootfs/pkgs/container/s6-rootfs#recommended-way-to-integrate-with-your-image-example
# ---------------------
# Build root filesystem
# ---------------------
FROM scratch AS rootfs

# Copy over base files
COPY ["./rootfs-s6-rc", "/"]

# Install S6
COPY --from=yanhao98/s6-rootfs@sha256:f45b9d31f0ed255f1967f868e28649bcd3ad7f533166c4f94ab9c1b35f7acd2c ["/", "/"]


# ---------------------
# Build image
# ---------------------
FROM alpine:3@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0

ENV TZ=Asia/Shanghai
RUN apk add alpine-conf && \
  /sbin/setup-timezone -z Asia/Shanghai && \
  apk del alpine-conf

ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data
RUN apk add --update --no-cache curl

WORKDIR /opt
COPY --from=rootfs ["/", "/"]

COPY --from=adguard/adguardhome:latest@sha256:3a143e6c071cd72b1aa5aa46ba0205a86f085d54daca94b7fc7ab6759e3fb6fa ["/opt/adguardhome", "/opt/adguardhome"]
VOLUME ["/opt/adguardhome/work", "/opt/adguardhome/conf"]

COPY --from=yanhao98/caddy-dns-cloudflare:latest@sha256:16d4b2e73e1bdfbc016039dbfe972f2dea64825ff1bbc3ede6eefc929613591a ["/usr/bin/caddy", "/opt/caddy/caddy"]

# S6 configuration - not required
# See: https://github.com/just-containers/s6-overlay#customizing-s6-overlay-behaviour
# ENV S6_KEEP_ENV=1
# ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2
# ENV S6_CMD_RECEIVE_SIGNALS=1

# Important, this is required for S6 to work
ENTRYPOINT ["/init"]