# https://github.com/n0rthernl1ghts/s6-rootfs/pkgs/container/s6-rootfs#recommended-way-to-integrate-with-your-image-example
# ---------------------
# Build root filesystem
# ---------------------
FROM scratch AS rootfs

# Copy over base files
COPY ["./rootfs-s6-rc", "/"]

# Install S6
COPY --from=yanhao98/s6-rootfs@sha256:e073f2b79d697701365029033da2406781f07859397570a66dae48b9c4989ed8 ["/", "/"]


# ---------------------
# Build image
# ---------------------
FROM alpine:3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d

ENV TZ=Asia/Shanghai
RUN apk add alpine-conf && \
  /sbin/setup-timezone -z Asia/Shanghai && \
  apk del alpine-conf

ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data
RUN apk add --update --no-cache curl

WORKDIR /opt
COPY --from=rootfs ["/", "/"]

COPY --from=adguard/adguardhome:latest@sha256:d16cc7517ab96f843e7f8bf8826402dba98f5e6b175858920296243332391589 ["/opt/adguardhome", "/opt/adguardhome"]
VOLUME ["/opt/adguardhome/work", "/opt/adguardhome/conf"]

COPY --from=yanhao98/caddy-dns-cloudflare:latest@sha256:5ac53e3f777d51ac4b04e6106cce5fa74ba60b64d5e850efb82bcf61d0765e0c ["/usr/bin/caddy", "/opt/caddy/caddy"]

# S6 configuration - not required
# See: https://github.com/just-containers/s6-overlay#customizing-s6-overlay-behaviour
# ENV S6_KEEP_ENV=1
# ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2
# ENV S6_CMD_RECEIVE_SIGNALS=1

# Important, this is required for S6 to work
ENTRYPOINT ["/init"]