#!/command/with-contenv sh
# shellcheck shell=sh

# sleep 3

# Function to check if a port is open using netcat
check_port() {
  echo "🔄 Checking if $1:$2 is available..."
  host=$1
  port=$2
  nc -z $host $port >/dev/null 2>&1
}


# Wait for Caddy to be fully available
while ! check_port 127.0.0.1 80; do
  sleep 5
done

# Wait for AdGuardHome to be fully available
while ! check_port 127.0.0.1 53; do
  sleep 5
done


echo "🎉 All dependencies are up. Starting ..."
tail -f /dev/null
